# https://www.youtube.com/watch?v=i4T1PNQZsiY
- hosts: es01
  become: yes
  tasks:
    - name: Node Master
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: 'node.master: true'
        replace: 'node.master: false'
    - name: Node Name
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: 'node.name: master'
        replace: 'node.name: es01'
#    - name: Node Network
#      replace:
#        path: /etc/elasticsearch/elasticsearch.yml
#        regexp: '\"localhost", "192.168.1.125"\'
#        replace: '"localhost", "192.168.1.127"'
- hosts: es02
  become: yes
  tasks:
    - name: Node Name
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: 'node.master: true'
        replace: 'node.master: false'
    - name: Node Name
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: 'node.name: master'
        replace: 'node.name: es02'
#    - name: Node Network
#      replace:
#        path: /etc/elasticsearch/elasticsearch.yml
#        regexp: '["localhost", "192.168.1.125"]'
#        replace: '["localhost", "192.168.1.128"]'
...
